version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/fitjourney
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - mysql
    networks:
      - fitjourney-network

  mysql:
    image: mysql:8.0.29
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fitjourney
    ports:
      - "3306:3306"
    networks:
      - fitjourney-network

networks:
  fitjourney-network:
    driver: bridge
